[package]
name = "smtp_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lettre = "0.11.7"
trust-dns-resolver = "0.23.2"
email-address-parser = "2.0.0"
